In [1]:
list1 = [0 for x in range(975)]
list2 = [1 for x in range(25)]

list_label = list1 + list2

list3 = [0 for x in range(970)]
list4 = [1,1,1,1,1]
list5 = [0,0,0,0,0,0,0,0,0,0]
list6 = [1 for x in range(15)]

list_pred = list3 + list4 + list5 + list6

print(list_label[970:])
print(list_pred[970:])

[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [3]:
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score

y_test = np.array(list_label)
y_pred = np.array(list_pred)

print("오차 행렬")
print(confusion_matrix(y_test, y_pred))

print("\n==== 정확도, 정밀도, 재현율 ====")
print("정확도: ", accuracy_score(y_test, y_pred))
print("정밀도: ", precision_score(y_test, y_pred))
print("재현율: ", recall_score(y_test, y_pred))

오차 행렬
[[970   5]
 [ 10  15]]

==== 정확도, 정밀도, 재현율 ====
정확도:  0.985
정밀도:  0.75
재현율:  0.6


In [4]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

iris = load_iris()
iris_data = iris.data
iris_label = iris.target

X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)

dt_clf = DecisionTreeClassifier(random_state=11)

dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)

In [5]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score

print("오차 행렬")
print(confusion_matrix(y_test, pred))
print()

print('예측 정확도: {0: .4f}'.format(accuracy_score(y_test,pred)))
print()

print('1 정밀도: ', precision_score(y_test, pred, average=None))
print('2 정밀도: ', precision_score(y_test, pred, average="micro"))
print('3 정밀도: ', precision_score(y_test, pred, average="micro"))
print('4 정밀도: ', precision_score(y_test, pred, average="weighted"))
print()

print('1 재현률: ', recall_score(y_test, pred, average=None))
print('2 재현률: ', recall_score(y_test, pred, average="micro"))
print('3 재현률: ', recall_score(y_test, pred, average="micro"))
print('4 재현률: ', recall_score(y_test, pred, average="weighted"))

오차 행렬
[[ 9  0  0]
 [ 0 10  0]
 [ 0  2  9]]

예측 정확도:  0.9333

1 정밀도:  [1.         0.83333333 1.        ]
2 정밀도:  0.9333333333333333
3 정밀도:  0.9333333333333333
4 정밀도:  0.9444444444444445

1 재현률:  [1.         1.         0.81818182]
2 재현률:  0.9333333333333333
3 재현률:  0.9333333333333333
4 재현률:  0.9333333333333333


In [6]:
from sklearn.preprocessing import Binarizer

X = [[1,-1,2],
     [2,0,0],
     [0,1.1,1.2]]

binarizer = Binarizer(threshold=1.1)
print(binarizer.fit_transform(X))

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [7]:
from sklearn.preprocessing import LabelBinarizer

def fillna(df):
    df['Age'].fillna(df['Age'].mean(), inplace=True)
    df['Cabin'].fillna('N', inplace=True)
    df['Embarked'].fillna('N', inplace=True)
    df['Fare'].fillna(0,inplace=True)
    return df

def drop_features(df):
    df.drop(['PassengerId', 'Name', 'Ticket'], axis=1, inplace=True)
    return df

def format_features(df):
    df['Cabin'] = df['Cabin'].str[:1]
    features = ['Cabin', 'Sex', 'Embarked']
    for feature in features:
        le = LabelBinarizer()
        le = le.fit(df[feature])
        df[feature] = le.transform(df[feature])
    return df

def transform_features(df):
    df = fillna(df)
    df = drop_features(df)
    df = format_features(df)
    return df

In [11]:
import pandas as pd
titanic_df = pd.read_csv('./titanic_train.csv')
y_titanic_df = titanic_df['Survived']
X_titanic_df = titanic_df.drop('Survived',axis=1)
X_titanic_df = transform_features(X_titanic_df)

C:\Users\yewon\AppData\Local\Temp\ipykernel_15828\1632640512.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)
C:\Users\yewon\AppData\Local\Temp\ipykernel_15828\1632640512.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For exa

In [12]:
from sklearn.model_selection import train_test_split
X_trian, X_test, y_train, y_test = train_test_split(X_titanic_df, y_titanic_df, test_size=0.2, random_state=11)

In [13]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

dt_clf = DecisionTreeClassifier(random_state=11)
rf_clf = RandomForestClassifier(random_state=11)
lr_clf = LogisticRegression(solver='liblinear')

In [1]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
from sklearn.preprocessing import Binarizer
from sklearn.metrics import f1_score

thresholds = [0.4, 0.45, 0.50, 0.55, 0.60]
pred_proba_c1 = pred_proba[:,1].reshape(-1,1)

for custom_threshold in thresholds:
    binarizer = Binarizer(threshold=custom_threshold).fit(pred_proba_c1)
    custom_predict = binarizer.transform(pred_proba_c1)
    print('임곗값:', custom_threshold)

    confusion = confusion_matrix(y_test, custom_predict)
    accuracy = accuracy_score(y_test, custom_predict)
    precision = precision_score(y_test, custom_predict)
    recall = recall_score(y_test, custom_predict)
    F1_score = f1_score(y_test, custom_predict)

    print('오차 행렬')
    print(confusion)
    print('정확도: {0:.4f}, 정밀도: {1:.4f}, 재현율: {2:.4f}'.format(accuracy, precision, recall))
    print('F1_Score: {0:.4f}'.format(F1_score))
    print()

NameError: name 'pred_proba' is not defined